# Installing NumPy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# Import NumPy

In [2]:
import numpy as np

# NumPy 

In [3]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [4]:
print(a[0])
print(a[1])

[1 2 3 4]
[5 6 7 8]


## 1. Creating Array

In [5]:
# np.array()
a = np.array([1,2,3,4,5])

In [6]:
a

array([1, 2, 3, 4, 5])

In [7]:
# np.zeros()
print ("Only Zero : ")
b = np.zeros(6)
b

Only Zero : 


array([0., 0., 0., 0., 0., 0.])

In [8]:
# np.ones()
print ("Only One : ")
c = np.ones(6)
c

Only One : 


array([1., 1., 1., 1., 1., 1.])

In [9]:
# np.arange()
print(np.arange(4))
print("or")
print(np.arange(0,10,2)) #(start, stop, step)

[0 1 2 3]
or
[0 2 4 6 8]


## 2. Add, Remove, Sort

In [10]:
arr = np.array([1,2,3,4,5,6,7,8])

In [11]:
# np.append()
np.append (arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [12]:
# np.delete()
np.delete(arr,1)  #delete index 1

array([1, 3, 4, 5, 6, 7, 8])

In [13]:
arr1 = np.array([2,5,3,4,9,1,7,8])

In [14]:
np.sort(arr1)

array([1, 2, 3, 4, 5, 7, 8, 9])

## 3. Shape and Size